### ISSUE TITLE
Refresh tests button have no effect

### ISSUE THREAD

**Issue by daimor** [intersystems-community/intersystems-testingmanager#20]
So, when I change `intersystems.testingManager.client.relativeTestRoot` and would like to refresh the list of available test, nothing changes, I have to reload the entire window, to see the effect.

**Comment by gjsjohnmurray** [comment]
@daimor thanks for creating this. Please try the dev build at https://github.com/intersystems-community/intersystems-testingmanager/suites/14475896944/artifacts/817843637 which should refresh its local tests tree automatically whenever you change that setting. The root node of each test tree will also offer a manual Refresh button.

**Comment by daimor** [comment]
Yep, working

**Comment by gjsjohnmurray** [comment]
Fix is in 0.23 which has just been published.
